### ISSUE TITLE
5주차 3번 노트북 구현 관련 문의

### ISSUE THREAD

**Issue by bt22dr** [public-ai/recsys_2020_3#17]
이번 3. Factorization Machine 알고리즘 및 구현하기.ipynb 노트북에서는 FM을 직접 구현해보았는데요. 실습 코드를 보면 마지막에 학습을 진행하고 그냥 끝나더라고요. 

이전에 진행하신 강의처럼, 새로 학습한 모델의 metric 평가 및 기존 모델과 비교하는 코드 또는 모델 이용해서 결과를 확인하는 코드 등이 추가되면 좋을것 같은데요. 혹시 관련 내용 추가하실 계획은 없으신지 문의 드립니다.

**Comment by sichu91** [comment]
피드백 감사드립니다.
6주차 강의에 추가예정입니다.
