### ISSUE TITLE
추천 시스템 구현 과정의 데이터 분석

### ISSUE THREAD

**Issue by shangrilar** [public-ai/recsys_2020_3#3]
안녕하세요. 

추천 시스템을 구현하는 과정에서 데이터를 뜯어 보는 작업을 진행할 텐데요.

기본적으로 sparsity, 이용자 성별, 연령대 분포, 아이템의 카테고리 분포, implicit/explicit feedback 데이터의 분포 분석 정도가 떠오르는데, 이외에 구현 과정에서 어떤 부분들을 살펴보면서 진행하는지 궁금합니다.

감사합니다.

**Comment by sichu91** [comment]
안녕하세요 답변이 늦어 죄송합니다.
먼저 질문 주신 '데이터 분석'이라는 표현이 모호하지만, 실제 추천 시스템 구현 사례 등을 통해 이해를 도모해 볼 수 있어 보입니다.
다음은 최규민님의 파이콘 발표[자료](https://www.slideshare.net/ssuser2fe594)입니다
쿠팡의 추천 시스템 변쳔사 [자료](https://deview.kr/data/deview/2019/presentation/[215]%20%E1%84%8F%E1%85%AE%E1%84%91%E1%85%A1%E1%86%BC%E1%84%8E%E1%85%AE%E1%84%8E%E1%85%A5%E1%86%AB%E1%84%89%E1%85%B5%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%86%B7%20%E1%84%87%E1%85%A7%E1%86%AB%E1%84%8E%E1%85%A5%E1%86%AB%E1%84%89%E1%85%A1%20(%E1%84%87%E1%85%A2%E1%84%91%E1%85%A9%E1%84%8B%E1%85%AD%E1%86%BC).pdf)입니다

'데이터 분석'이란 표현은 그 범위가 너무 넓아 하나의 답을 드리기보다는 사례를 제안 드렸는데, 강의 진행을 하다보면 하나씩 감을 잡으실 수 있으리라 믿습니다 :)
ifkakao2020에서 제가 발표할 내용도 질문주신 부분과 비슷한 맥락의 내용인데, 추후 강의에서 간단히 소개드리도록 하겠습니다.
