### ISSUE TITLE
user-based 협업 필터링 방식을 사용할 때 추천 결과 생성

### ISSUE THREAD

**Issue by bt22dr** [public-ai/recsys_2020_3#4]
week2.pdf 강의 자료 23 페이지에는 item-based 협업 필터링 방식을 사용할 때 특정 고객에게 추천 목록을 생성하기 위해 가중평균을 계산해서 선호도를 예측하는 방법이 잘 나와 있는데요. 혹시 user-based 협업 필터일 방식을 사용할 때는 어떻게 선호도를 예측할 수 있을까요?

**Comment by sichu91** [comment]
안녕하세요, 답변이 늦어 죄송합니다.
먼저 item-based 협업 필터링 방식을 통해 '특정 고객의 보지 못한 아이템에 대한 rating을 예측'하는 과정을 강의 중에 설명드렸는데요

이를 대칭적으로 사용하게 된다면 '특정 아이템을 보지 않은 유저에 대한 rating을 예측'할 수 있습니다. 즉, '특정 아이템이 주어졌을 때 어떤 유저에게 이것을 추천할 것인가'라는 문제를 풀 수 있게 됩니다.

그 외에도 '코끼리 냉장고에 집어넣기' 슬라이드에서 처럼 유사한 유저들끼리 클러스터를 만든 뒤 클러스터 내에서 추천을 시행하게 된다면 대단히 적은 자원으로 뛰어난 성능을 낼 수 있습니다.

강의시간에 소개드렸던 rating을 예측해 추천을 구현하는 방법은 수많은 방법 중 가장 간단한 수준의 예시일 뿐이며, 실제 커다란 시스템을 구현할 때는 여러 모델과 방법론들이 '조립'되는 것처럼 합쳐지게 됩니다.
따라서 'memory based CF에서 나온 유저의 유사도를 이용해 어떻게 추천시스템을 만들 수 있을까?'라는 것보다는
'이러이러한 추천 시스템을 만들고 싶은데, 여기에는 어떤 방법론들을 사용할 수 있을까?'라는 관점으로 보시는 게 더 좋을 것 같습니다.

지금 말씀드리는 내용은 2주차 강의만으로는 전부 이해하기 어려울 수 있으니 너무 급해마시고 천천히 강의를 들어주시면 감사하겠습니다 :)

**Comment by bt22dr** [comment]
week2의 2번째 노트북은 단순히 스타워즈나 링 같은 영화에 대해 유사한 영화를 유사도 순으로 보여주는 것으로 마무리가 되는데요. item-based RS도 배웠고 rating을 예측하는 방법도 다루었으니 실제로 특정 사용자에게 영화를 추천하는 것으로 예제가 마무리되었다면 어땠을까 싶어서요... 예를 들어, rating_df에서 user_id 2976인 사용자에게 무슨 영화를 추천할 것인지 목록을 실제로 뽑아보고 그 사용자가 본 영화들과 비교해보거나 하면 훨씬 더 강의 내용을 잘 체득할 수 있을것 같습니다.
