### ISSUE TITLE
코드 검토 요청

### ISSUE THREAD

**Issue by bt22dr** [public-ai/recsys_2020_3#5]
3주차 2번 노트북 41번 cell이 실행 결과가 다르게 나오네요. 

user_id = 285  
target_id = user_names[user_id]  
target_user = user_embedding_df.loc[target_id]  
print([artist_id2name[f] for f in artistset_per_user[user_id]])

이렇게 수정하면 동일하게 나옵니다.

**Comment by sichu91** [comment]
어느 부분인지 확인하기가 어렵네요.
추정컨대 말씀하신 셀 외에도 다른 부분도 수정을 하셔서 그런게 아닐까 짐작됩니다.
확인해본 결과 올라간 코드를 다른 수정 없이 돌렸을 때는 이상없이 작동합니다.

**Comment by bt22dr** [comment]
filled에 있는 코드를 똑같이 사용해서 다시 테스트해봤는데 여전히 똑같이 나오지 않네요.

혹시 `user_embedding_df`과 `artistset_per_user` 모두 행 인덱싱이 user_id로 되어 있는데 `user_embedding_df.loc[target_id]`에서 한 것처럼 `artistset_per_user[target_id]`가 아니라 `artistset_per_user.loc[target_id]`로 사용해야 하는게 아닐까요?

**Comment by sichu91** [comment]
정확히 어디 부분의 코드인지, 수정 이전의 코드를 올려주시면 확인해보도록 하겠습니다.
다만, 저는 filled의 코드를 다 시행한 뒤 올리고 있고
또 어제와 오늘 이틀 모두 몇 차례에 걸쳐 재구동해 본 결과 전혀 이상이 없었습니다.

**Comment by bt22dr** [comment]
2. 베이지안 개인화 랭킹 알고리즘의 개념 및 구현 노트북에서 (3) 유저의 취향과 비슷한 특성을 가진 아티스트 추천하기 부분입니다.

![image](https://user-images.githubusercontent.com/4475963/93069251-6e1c8680-f6b8-11ea-86ef-07d350990d76.png)

**Comment by sichu91** [comment]
아무리 생각해도 중간에 코드를 누락하거나 잘못 돌리신 게 아닐까 합니다.
오늘도 제가 다시 처음부터 돌려보았는데 잘 돌아가네요
혹시 ipynb 파일을 메일로 보내주실 수 있을까요?
dane.cb@kakaocorp.com입니다.

**Comment by bt22dr** [comment]
https://github.com/bt22dr/recsys_2020_3/blob/master/notes/week3/2.%20%EB%B2%A0%EC%9D%B4%EC%A7%80%EC%95%88%20%EA%B0%9C%EC%9D%B8%ED%99%94%20%EB%9E%AD%ED%82%B9%20%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98%EC%9D%98%20%EA%B0%9C%EB%85%90%20%EB%B0%8F%20%EA%B5%AC%ED%98%84.ipynb 입니다.

**Comment by sichu91** [comment]
![image](https://user-images.githubusercontent.com/39235119/94046801-1f839080-fe0c-11ea-92a7-4b2804b0e41b.png)

말씀하신 코드를 다운받아 실험해해보았는데, 저는 filled의 코드로 해야 잘 돌아갑니다.
정확한 에러코드를 말씀해주시진 않았지만,
loc를 통해 인덱스를 타는 경우 category로 세팅이 되어있어야 하지만, 그냥 300을 넣어주면 에러가 발생하게됩니다. 
`TypeError: cannot do label indexing on <class 'pandas.core.indexes.category.CategoricalIndex'> with these indexers [300] of <class 'int'>`

아니면 판다스의 버전 차이 때문에 현재 코드가 호환되고 있지 않을 수 있습니다.
제 경우에는 0.25.1 버전을 사용하고 있습니다.

**Comment by bt22dr** [comment]
저도 판다스 0.25.1로 나오네요.

위에 올려주신 코드 실행결과를 보면 [angelo badalamenti, ..., nine inch nails]가 나오는데
![image](https://user-images.githubusercontent.com/4475963/94163801-3933df00-fec3-11ea-92e1-b155e3648225.png)

제가 실행한 코드에서는 동일한 코드인데 결과가 [the clash, ..., nine inch nails]로 다르게 나와서 질문 드렸던 건데요.
![image](https://user-images.githubusercontent.com/4475963/94164080-8e6ff080-fec3-11ea-9e87-e304fce55929.png)

환경이 좀 달라서인지 뭔가 알 수 없는 이유인지 어쨌거나 결과가 좀 다르게 나올 수도 있나 보네요. 확인 감사합니다.
