### ISSUE TITLE
실서비스에서 BPR 알고리즘 적용을 위해 Implicit 라이브러리를 사용해도 될까요?

### ISSUE THREAD

**Issue by bt22dr** [public-ai/recsys_2020_3#6]
이번주 수업에서는 암묵적 데이터를 위한 BPR 알고리즘 구현에 Implicit 라이브러리를 사용하했는데요. 실제로 카카오에서도 BPR 알고리즘 구현에 Implicit 라이브러리를 사용하시나요? 아니면 직접 구현해서 사용하시나요? 

사용자나 아이템이 많아서 데이터의 규모가 매우 큰 상황에도 문제없이 사용할 수 있는지, 실서비스에서 신뢰성 있게 사용해도 되는 라이브러리인지(버전이 0.4 대라서 ^^;;) 궁금합니다.

**Comment by sichu91** [comment]
사용하셔도 상관은 없지만, 오픈 소스 패키지가 그렇듯 실패에 대한 보장을 하지는 않습니다.
성능이나 scalability는 큰 무리가 없다고 생각합니다.

카카오에서는 추천서비스를 위해 자체적으로 buffalo를 개발하였고, implicit과 마찬가지로 오픈소스로 공개되었습니다.
[buffalo](https://github.com/kakao/buffalo)도 추천드립니다 ^^
